version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/assessment_app
    volumes:
      - ./:/var/www/assessment_app   # syncs code
      - ./storage:/var/www/assessment_app/storage
      - ./vendor:/var/www/assessment_app/vendor
      - ./env_prod/.env:/var/www/assessment_app/.env:ro   # keeps .env safe
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:
